### ISSUE TITLE
How to run this diffusion model with transfer learning?

### ISSUE THREAD

**Issue by ghost** [Derekabc/DMWeeds#1]
Hello, I am interested in your work. 

I was wondering how to run this model?

**Comment by DongChen06** [comment]
Hi, thanks for your interest. actually, I did not include the diffusion model here, you can go to https://github.com/openai/guided-diffusion for reference. To practice, you may also implement and look at this repo first: https://github.com/openai/improved-diffusion. please feel free to let me know if you have any questions.

**Comment by zezeze97** [comment]
Hi, I have encountered several problems while trying to reproduce transfer diffsuion models and would like to ask you for advice. 
 1.  Will too many trained iters for diffsusion and guided classifiers cause overfitting? According to the settings in your paper, which are 300000 iters and 200000 iters, respectively, training time with v100 exceeds 24h. The cost of computing resources trying to reproduce is relatively large. This is my experimental configuration for diffusion and guided classifier. The final experimental results were not very satisfactory, and the FIDs of ADM and ADM-G were 47.25 and 49.14, respectively.
 
Diffusion:
MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond True --diffusion_steps 1000 --image_size 256 --learn_sigma True --noise_schedule linear --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True"
TRAIN_FLAGS="--lr 1e-4 --batch_size 4 --lr_anneal_steps 300000"
python scripts/image_train.py --data_dir ./datasets/CottonWeedID-sub10 $MODEL_FLAGS $TRAIN_FLAGS --pretrained_ckpt ./Guided-Diffusion-Pretrained-Ckpts/256x256_diffusion.pt

Guided-Classifier:
TRAIN_FLAGS="--iterations 200000 --anneal_lr True --batch_size 8 --lr 3e-4 --save_interval 10000 --weight_decay 0.05"
CLASSIFIER_FLAGS="--image_size 256 --classifier_attention_resolutions 32,16,8 --classifier_depth 2 --classifier_width 128 --classifier_pool attention --classifier_resblock_updown True --classifier_use_scale_shift_norm True"
CUDA_VISIBLE_DEVICES=0 python scripts/classifier_train.py --data_dir ./datasets/CottonWeedID-sub10 --pretrained_ckpt ./Guided-Diffusion-Pretrained-Ckpts/256x256_classifier.pt  $TRAIN_FLAGS $CLASSIFIER_FLAGS

2. Configuration at sampling time:
ADM:
SAMPLE_FLAGS="--batch_size 2  --num_samples 4685 --timestep_respacing 250"
MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond True --diffusion_steps 1000 --image_size 256 --learn_sigma True --noise_schedule linear --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True"
CUDA_VISIBLE_DEVICES=3 python ./scripts/image_sample.py $MODEL_FLAGS --model_path ./Guided-Diffusion-Output/diffusion/ema_0.9999_300000.pt $SAMPLE_FLAGS

ADM-G:
SAMPLE_FLAGS="--batch_size 2  --num_samples 4685 --timestep_respacing 250"
MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond True --diffusion_steps 1000 --image_size 256 --learn_sigma True --noise_schedule linear --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True"
python ./scripts/classifier_sample.py $MODEL_FLAGS --classifier_scale 1.0 --classifier_path ./Guided-Diffusion-Output/classifier/model199999.pt --model_path ./Guided-Diffusion-Output/diffusion/ema_0.9999_300000.pt $SAMPLE_FLAGS

Does the timestep respacing parameter need to be reconfigured at sampling time, or does the reverse process step=1000? In addition, when calculating the FID, I chose to generate the same number of images as the training data.

**Comment by DongChen06** [comment]
Hi, could you contact me via email? Let's look at the issues together.
