### ISSUE TITLE
train

### ISSUE THREAD

**Issue by ONobody** [Derekabc/DMWeeds#3]
How can I use your model to train my own data set Thank you

**Comment by DongChen06** [comment]
Hi, you can follow the instructions: https://github.com/openai/guided-diffusion, please feel free to let me know when you face any issues.

**Comment by ONobody** [comment]
hello Let me ask you again what the location of the data folder is when training your own data set using guided - diffusion
and How to change the location where the model is saved。The system disk of the server is small, and I want to save it to the data disk.

**Comment by DongChen06** [comment]
You may find them in: https://github.com/openai/guided-diffusion/blob/22e0df8183507e13a7813f8d38d51b072ca1e67c/scripts/classifier_train.py#L182

and 

https://github.com/openai/guided-diffusion/blob/22e0df8183507e13a7813f8d38d51b072ca1e67c/guided_diffusion/train_util.py#L232

**Comment by ONobody** [comment]
I'm sorry, I still don't understand some things.
May I add your contact information?
In order to communicate better, thank you very much.

**Comment by ONobody** [comment]
@DongChen06 Thank you very much. How can I train my data set according to the weight fine-tuning provided by the author?
What codes need to be changed in classifier_train.py or elsewhere? thank you  
I'm a bit stupid

**Comment by DongChen06** [comment]
You may contact me via chendondon19930606@gmail.com
